[package]
name = 'q2r'
publish = false
version = '0.1.0'
edition = '2024'
rust-version = '1.85'

[lib]
crate-type = [ 'rlib', 'staticlib' ]
name = 'q2r'

[[bin]]
name = 'document'
path = 'document.rs'

[dependencies]
extendr-api = '0.9.0'
tree-sitter = '0.26'
streaming-iterator = '0.1'
hashlink = '0.11'

[dependencies.pampa]
git = 'https://github.com/quarto-dev/q2'
rev = '6e8795559783d7e0e6bc00b660e6eb39087d95a1'
default-features = false

[dependencies.tree-sitter-qmd]
git = 'https://github.com/quarto-dev/q2'
rev = '6e8795559783d7e0e6bc00b660e6eb39087d95a1'

[dependencies.quarto-source-map]
git = 'https://github.com/quarto-dev/q2'
rev = '6e8795559783d7e0e6bc00b660e6eb39087d95a1'

[dependencies.quarto-error-reporting]
git = 'https://github.com/quarto-dev/q2'
rev = '6e8795559783d7e0e6bc00b660e6eb39087d95a1'

[profile.release]
lto = true
codegen-units = 1
