[package]
name = 'q2r'
publish = false
version = '0.1.0'
edition = '2024'
rust-version = '1.85'

[lib]
crate-type = [ 'rlib', 'staticlib' ]
name = 'q2r'

[[bin]]
name = 'document'
path = 'document.rs'

[dependencies]
extendr-api = '0.9.0'
tree-sitter = '0.25.10'
hashlink = '0.11'

[dependencies.pampa]
git = 'https://github.com/quarto-dev/q2'
rev = '349148ae8d9d8e19d9c1075f564a3c5d43a43a4a'
default-features = false

[dependencies.tree-sitter-qmd]
git = 'https://github.com/quarto-dev/q2'
rev = '349148ae8d9d8e19d9c1075f564a3c5d43a43a4a'

[dependencies.quarto-source-map]
git = 'https://github.com/quarto-dev/q2'
rev = '349148ae8d9d8e19d9c1075f564a3c5d43a43a4a'

[dependencies.quarto-error-reporting]
git = 'https://github.com/quarto-dev/q2'
rev = '349148ae8d9d8e19d9c1075f564a3c5d43a43a4a'

[profile.release]
lto = true
codegen-units = 1
