quarto_web_root = function() {
  testthat::test_path("..", "fixtures", "quarto-web")
}

quarto_web_available = function() {
  root = quarto_web_root()
  dir.exists(root) && file.exists(file.path(root, "_quarto.yml"))
}

skip_if_no_quarto_web = function() {
  if (!quarto_web_available()) {
    testthat::skip("quarto-web submodule not checked out (run `git submodule update --init`)")
  }
}

quarto_web_files = function() {
  root = quarto_web_root()
  files = list.files(root, pattern = "\\.qmd$", recursive = TRUE, full.names = TRUE)
  rel = substr(files, nchar(root) + 2L, nchar(files))
  # `list.files()` orders by the active LC_COLLATE, so the generated sweep
  # files would churn across locales (C vs UTF-8). Force byte order.
  sort(rel, method = "radix")
}

quarto_web_read = function(rel) {
  paste(readLines(file.path(quarto_web_root(), rel), warn = FALSE), collapse = "\n")
}

has_error_diagnostics = function(x) {
  diags = x@diagnostics
  if (!length(diags)) return(FALSE)
  any(vapply(diags, function(d) identical(d@kind, "error"), logical(1)))
}

expect_no_error_diagnostics = function(actual) {
  act_lab = testthat::quasi_label(rlang::enquo(actual), arg = "actual")
  diags = actual@diagnostics
  errs = if (length(diags)) {
    Filter(function(d) identical(d@kind, "error"), diags)
  } else list()
  if (length(errs) == 0L) {
    testthat::expect(TRUE, "ok")
  } else {
    rendered = vapply(errs, function(d) format(d, color = FALSE), character(1L))
    testthat::expect(
      FALSE,
      sprintf(
        "%s has %d error diagnostic(s):\n\n%s",
        act_lab$lab, length(errs), paste(rendered, collapse = "\n\n")
      )
    )
  }
  invisible(actual)
}

number_ast_lines = function(lines) {
  w = max(2L, nchar(as.character(length(lines))))
  sprintf(paste0("%", w, "d │ %s"), seq_along(lines), lines)
}

diff_ast_lines = function(act_lines, exp_lines, x_arg, y_arg) {
  if (identical(act_lines, exp_lines)) return(character())
  withr::local_options(width = max(getOption("width"), 200L))
  d = diffobj::diffChr(
    number_ast_lines(act_lines),
    number_ast_lines(exp_lines),
    mode = "sidebyside",
    format = if (cli::num_ansi_colors() > 1L) "ansi8" else "raw",
    line.limit = 30L,
    tar.banner = x_arg,
    cur.banner = y_arg
  )
  as.character(d)
}

expect_ts_ast_equal = function(actual, expected) {
  act_lab = testthat::quasi_label(rlang::enquo(actual),   arg = "actual")
  exp_lab = testthat::quasi_label(rlang::enquo(expected), arg = "expected")
  if (identical(q2r:::ts_tree_to_list(actual), q2r:::ts_tree_to_list(expected))) {
    testthat::expect(TRUE, "ok")
    return(invisible(actual))
  }
  withr::local_options(cli.unicode = TRUE)
  act_lines = q2r:::ts_tree_lines(actual)
  exp_lines = q2r:::ts_tree_lines(expected)
  diff = diff_ast_lines(act_lines, exp_lines, act_lab$lab, exp_lab$lab)
  testthat::expect(
    length(diff) == 0,
    sprintf(
      "ts ast mismatch (actual: %d lines, expected: %d lines):\n%s",
      length(act_lines), length(exp_lines),
      paste(diff, collapse = "\n")
    )
  )
  invisible(actual)
}

expect_pd_ast_equal = function(actual, expected) {
  act_lab = testthat::quasi_label(rlang::enquo(actual),   arg = "actual")
  exp_lab = testthat::quasi_label(rlang::enquo(expected), arg = "expected")
  if (identical(q2r:::pandoc_to_list(actual), q2r:::pandoc_to_list(expected))) {
    testthat::expect(TRUE, "ok")
    return(invisible(actual))
  }
  withr::local_options(cli.unicode = TRUE)
  act_lines = q2r:::pandoc_tree_lines(actual)
  exp_lines = q2r:::pandoc_tree_lines(expected)
  diff = diff_ast_lines(act_lines, exp_lines, act_lab$lab, exp_lab$lab)
  testthat::expect(
    length(diff) == 0,
    sprintf(
      "pd ast mismatch (actual: %d lines, expected: %d lines):\n%s",
      length(act_lines), length(exp_lines),
      paste(diff, collapse = "\n")
    )
  )
  invisible(actual)
}

update_tests = function(target, files, mtime_paths, gen_func, skip_map = list()) {
  if (!file.exists(target)) {
    writeLines(character(), target)
  }

  dep_mtimes = file.info(mtime_paths)$mtime
  target_mtime = file.info(target)$mtime
  target_is_empty = file.info(target)$size == 0

  needs_regen = target_is_empty || any(dep_mtimes > target_mtime, na.rm = TRUE)
  if (!needs_regen) return(invisible(FALSE))

  message("Generating ", target)
  blocks = lapply(files, gen_func, skip_map = skip_map)
  header = c(
    "# Generated by helper-quarto-web.R, do not edit by hand",
    ""
  )
  body = unlist(lapply(blocks, function(b) c(b, "")), use.names = FALSE)
  writeLines(c(header, body), target)
  invisible(TRUE)
}

maybe_regenerate_quarto_web_tests = function() {
  if (nzchar(Sys.getenv("CI"))) return(invisible(FALSE))
  gen_src = "_gen-quarto-web.R"
  if (!file.exists(gen_src)) return(invisible(FALSE))
  if (!quarto_web_available()) return(invisible(FALSE))

  gen_env = new.env(parent = globalenv())
  source(gen_src, local = gen_env)

  files = quarto_web_files()
  fixture_paths = file.path(quarto_web_root(), files)
  source_deps = c(gen_src, "helper-quarto-web.R")
  mtime_paths = c(fixture_paths, source_deps)

  variants = list(
    list(target = "test-quarto-web-ts-rt.R", fn = "gen_ts_rt_test", id = "ts_rt"),
    list(target = "test-quarto-web-pd-rt.R", fn = "gen_pd_rt_test", id = "pd_rt")
  )

  for (v in variants) {
    update_tests(
      target = v$target,
      files = files,
      mtime_paths = mtime_paths,
      gen_func = local({
        gen = gen_env[[v$fn]]
        function(rel, skip_map) gen(rel, skip_map = skip_map)
      }),
      skip_map = gen_env$QUARTO_WEB_SKIP[[v$id]]
    )
  }

  invisible(TRUE)
}

maybe_regenerate_quarto_web_tests()
