quarto_web_root = function() {
  testthat::test_path("..", "fixtures", "quarto-web")
}

quarto_web_available = function() {
  root = quarto_web_root()
  dir.exists(root) && file.exists(file.path(root, "_quarto.yml"))
}

skip_if_no_quarto_web = function() {
  if (!quarto_web_available()) {
    testthat::skip("quarto-web submodule not checked out (run `git submodule update --init`)")
  }
}

quarto_web_files = function() {
  root = quarto_web_root()
  files = list.files(root, pattern = "\\.qmd$", recursive = TRUE, full.names = TRUE)
  substr(files, nchar(root) + 2L, nchar(files))
}

quarto_web_read = function(rel) {
  paste(readLines(file.path(quarto_web_root(), rel), warn = FALSE), collapse = "\n")
}

has_error_diagnostics = function(x) {
  diags = x@diagnostics
  if (!length(diags)) return(FALSE)
  any(vapply(diags, function(d) identical(d@kind, "error"), logical(1)))
}

ts_kind_tree = function(node) {
  list(
    kind     = node@kind,
    named    = node@is_named,
    field    = node@field_name %||% NA_character_,
    children = lapply(node@children@content, ts_kind_tree)
  )
}

ts_tree_kind_tree = function(tree) ts_kind_tree(tree@root)

compare_ts_kind = function(a, b) identical(ts_tree_kind_tree(a), ts_tree_kind_tree(b))

compare_pd_ast = function(a_text, b_text, filename = "<cmp>") {
  identical(
    q2r:::pandoc_to_list(pampa_parse_pd(a_text)),
    q2r:::pandoc_to_list(pampa_parse_pd(b_text))
  )
}

update_tests = function(target, files, mtime_paths, gen_func, skip_map = list()) {
  if (!file.exists(target)) {
    writeLines(character(), target)
  }

  dep_mtimes = file.info(mtime_paths)$mtime
  target_mtime = file.info(target)$mtime
  target_is_empty = file.info(target)$size == 0

  needs_regen = target_is_empty || any(dep_mtimes > target_mtime, na.rm = TRUE)
  if (!needs_regen) return(invisible(FALSE))

  message("Generating ", target)
  blocks = lapply(files, gen_func, skip_map = skip_map)
  header = c(
    "# Generated by helper-quarto-web.R, do not edit by hand",
    ""
  )
  body = unlist(lapply(blocks, function(b) c(b, "")), use.names = FALSE)
  writeLines(c(header, body), target)
  invisible(TRUE)
}

maybe_regenerate_quarto_web_tests = function() {
  if (nzchar(Sys.getenv("CI"))) return(invisible(FALSE))
  gen_src = "../../R/tests.R"
  if (!file.exists(gen_src)) return(invisible(FALSE))
  if (!quarto_web_available()) return(invisible(FALSE))

  gen_env = new.env(parent = globalenv())
  source(gen_src, local = gen_env)

  files = quarto_web_files()
  fixture_paths = file.path(quarto_web_root(), files)
  source_deps = c(gen_src, "helper-quarto-web.R")
  mtime_paths = c(fixture_paths, source_deps)

  variants = list(
    list(target = "test-quarto-web-ts-rt.R",       fn = "gen_ts_rt_test",       id = "ts_rt"),
    list(target = "test-quarto-web-pd-rt.R",       fn = "gen_pd_rt_test",       id = "pd_rt"),
    list(target = "test-quarto-web-pampa-ts-rt.R", fn = "gen_pampa_ts_rt_test", id = "pampa_ts_rt"),
    list(target = "test-quarto-web-pampa-pd-rt.R", fn = "gen_pampa_pd_rt_test", id = "pampa_pd_rt")
  )

  for (v in variants) {
    update_tests(
      target = v$target,
      files = files,
      mtime_paths = mtime_paths,
      gen_func = local({
        gen = gen_env[[v$fn]]
        function(rel, skip_map) gen(rel, skip_map = skip_map)
      }),
      skip_map = gen_env$QUARTO_WEB_SKIP[[v$id]]
    )
  }

  invisible(TRUE)
}

maybe_regenerate_quarto_web_tests()
