# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib q2r, .registration = TRUE
NULL

#' Parse QMD text with pampa.
#'
#' Returns a list with `tree` (tree-sitter CST text), `cst` (structured
#' tree-sitter CST as a nested tagged list), `diagnostics`, `native`
#' (Pandoc native-format text), and `ast` (tagged nested list suitable
#' for conversion to S7 `pandoc` objects).
#' @export
pampa_parse_impl <- function(text, filename) .Call(wrap__pampa_parse_impl, text, filename)

# nolint end
