# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib q2r, .registration = TRUE
NULL

#' Parse QMD text with pampa and return the Pandoc AST.
#'
#' Returns a list with `pd_ast` (tagged nested list suitable for
#' conversion to S7 `pandoc` objects, or `NULL` if parsing failed) and
#' `diagnostics` (list of structured diagnostic records that can be
#' rendered via `pampa_diag_format_impl`).
#' @export
pampa_parse_pd_impl <- function(text, filename) .Call(wrap__pampa_parse_pd_impl, text, filename)

#' Parse QMD text with tree-sitter and return the tree-sitter AST.
#'
#' Returns a list with `ts_ast` (structured tree-sitter AST as a nested
#' tagged list) and `diagnostics` (list of structured diagnostic records
#' from pampa's QMD reader). The tree-sitter AST itself never fails to
#' produce; `diagnostics` surfaces higher-level pampa parse errors.
#' @export
pampa_parse_ts_impl <- function(text, filename) .Call(wrap__pampa_parse_ts_impl, text, filename)

#' Capture pampa's tree-sitter debug dump for QMD text.
#'
#' Returns the lines of the `print_whole_tree` output that pampa emits
#' to stderr when run with `-v`. Primarily a testing helper for
#' cross-checking the structured `ts_ast` against pampa's own view.
#' @export
pampa_tree_impl <- function(text, filename) .Call(wrap__pampa_tree_impl, text, filename)

#' Render QMD text to Pandoc's native AST format.
#'
#' Returns the lines of `pampa::writers::native::write` applied to the
#' parsed Pandoc document, or an empty vector if parsing failed.
#' Primarily a testing helper.
#' @export
pampa_native_impl <- function(text, filename) .Call(wrap__pampa_native_impl, text, filename)

#' Render QMD input through pampa's own QMD writer (text/file path).
#'
#' Parses `text` with pampa's QMD reader and writes the resulting Pandoc
#' AST back out using `pampa::writers::qmd::write`. Primarily a testing
#' helper for comparing against the R-side `to_qmd()` implementations.
#' Returns a list with `text` (the rendered QMD) and `diagnostics`.
#' @export
pampa_write_qmd_text_impl <- function(text, filename) .Call(wrap__pampa_write_qmd_text_impl, text, filename)

#' Render an R-constructed Pandoc AST through pampa's QMD writer.
#'
#' Takes a tagged-list Pandoc AST (same shape emitted by
#' `pampa_parse_pd_impl`), reconstructs a `pampa::pandoc::Pandoc` value,
#' and writes it out via `pampa::writers::qmd::write`. Returns a list
#' with `text` (rendered QMD, or `NULL` on error) and `diagnostics`
#' (any writer diagnostics; empty on success).
#' @export
pampa_write_qmd_ast_impl <- function(r_ast) .Call(wrap__pampa_write_qmd_ast_impl, r_ast)

#' Pretty-print a diagnostic by reconstructing it from its slot values.
#'
#' Accepts the structured fields carried by a `pampa_diagnostic` S7
#' object (`kind`, `code`, `title`, `problem`, `details`, `hints`,
#' `location`) together with the original source text, filename, and
#' a flag controlling OSC 8 terminal hyperlinks. Returns the ariadne
#' rendering (which includes ANSI colour codes); callers that want
#' colourless output should strip ANSI afterward.
#' @export
pampa_diag_format_impl <- function(kind, code, title, problem, details, hints, location, source_text, source_filename, hyperlinks) .Call(wrap__pampa_diag_format_impl, kind, code, title, problem, details, hints, location, source_text, source_filename, hyperlinks)

# nolint end
