QUARTO_WEB_SKIP = list(
  ts_rt = list(
    "_tools/screenshots/examples/quarto-demo/crossref-jupyter.qmd" = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "bug-reports.qmd"                                              = "q2#TBD-inline-span-triple-backtick (inline code span wrapping ` ```{lang} ` rejected)",
    "docs/advanced/environment-vars.qmd"                           = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/authoring/create-citeable-articles.qmd"                  = "q2#TBD-footnote-indent-continuation (footnote-continuation 4-space indent triggers Q-2-35; structurally analogous to q2#196 but for footnotes)",
    "docs/authoring/cross-references.qmd"                          = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/authoring/markdown-basics.qmd"                           = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/authoring/tables.qmd"                                    = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/blog/posts/2023-12-07-quarto-dashboards-demo/index.qmd"  = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/blog/posts/2024-01-24-1.4-release/index.qmd"             = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/blog/posts/2024-12-04-websites-workshop/index.qmd"       = "q2#TBD-underscore-prefix-emphasis (Q-2-5 on _filename.ext identifiers)",
    "docs/blog/posts/2025-10-20-quarto-wizard-1-0-0/index.qmd"     = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/blog/posts/2025-11-24-conf-talk-videos/index.qmd"        = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/computations/caching.qmd"                                = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/computations/julia.qmd"                                  = "q2#TBD-apostrophe-quote-close (Q-2-9/Q-2-10 on possessive apostrophes)",
    "docs/computations/r.qmd"                                      = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/dashboards/_examples/penguins-obervable.qmd"             = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/extensions/filters.qmd"                                  = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/extensions/lua.qmd"                                      = "q2#TBD-attr-key-before-class (Q-2-3 fires on {key='v' .class} attribute ordering)",
    "docs/extensions/project-types.qmd"                            = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/get-started/authoring/jupyter.qmd"                       = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/authoring/rstudio.qmd"                       = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/computations/jupyter.qmd"                    = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/computations/positron.qmd"                   = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/computations/vscode.qmd"                     = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/hello/jupyter.qmd"                           = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/hello/neovim.qmd"                            = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/hello/text-editor.qmd"                       = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/hello/vscode.qmd"                            = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/interactive/layout.qmd"                                  = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/interactive/ojs/libraries.qmd"                           = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/interactive/ojs/ojs-cells.qmd"                           = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/interactive/ojs/shiny.qmd"                               = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/interactive/shiny/execution.qmd"                         = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/interactive/shiny/index.qmd"                             = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/manuscripts/authoring/_citations.qmd"                    = "q2#TBD-attr-key-before-class (Q-2-3 fires on {key='v' .class} attribute ordering)",
    "docs/manuscripts/authoring/_structure.qmd"                    = "q2#TBD-inline-span-triple-backtick (inline code span wrapping ` ```{lang} ` rejected)",
    "docs/manuscripts/authoring/_visual-editor.qmd"                = "q2#TBD-attr-key-before-class (Q-2-3 fires on {key='v' .class} attribute ordering)",
    "docs/manuscripts/components.qmd"                              = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/manuscripts/index.qmd"                                   = "q2#TBD-attr-key-before-class (Q-2-3 fires on {key='v' .class} attribute ordering)",
    "docs/output-formats/html-code.qmd"                            = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/output-formats/html-themes-more.qmd"                     = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/output-formats/hugo.qmd"                                 = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/output-formats/ms-word-templates.qmd"                    = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/output-formats/typst-custom.qmd"                         = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/presentations/revealjs/presenting.qmd"                   = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/projects/code-execution.qmd"                             = "q2#TBD-apostrophe-quote-close (Q-2-9/Q-2-10 on possessive apostrophes)",
    "docs/projects/quarto-projects.qmd"                            = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/projects/virtual-environments.qmd"                       = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/publishing/github-pages.qmd"                             = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/tools/_jupyter-lab-extension-install.qmd"                = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/tools/jupyter-lab-extension.qmd"                         = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/tools/jupyter-lab.qmd"                                   = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/visual-editor/options.qmd"                               = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/visual-editor/technical.qmd"                             = "q2#TBD-inline-span-triple-backtick (inline code span wrapping ` ```{lang} ` rejected)",
    "docs/websites/website-drafts.qmd"                             = "q2#TBD-apostrophe-quote-close (Q-2-9/Q-2-10 on possessive apostrophes)",
    "docs/websites/website-listings-custom.qmd"                    = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/websites/website-listings.qmd"                           = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/websites/website-navigation.qmd"                         = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/websites/website-tools.qmd"                              = "q2#TBD-apostrophe-quote-close (Q-2-9/Q-2-10 on possessive apostrophes)"
  ),
  pd_rt = list(
    "_tools/screenshots/examples/quarto-demo/crossref-jupyter.qmd" = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "bug-reports.qmd"                                              = "q2#TBD-inline-span-triple-backtick (inline code span wrapping ` ```{lang} ` rejected)",
    "docs/advanced/environment-vars.qmd"                           = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/authoring/create-citeable-articles.qmd"                  = "q2#TBD-footnote-indent-continuation (footnote-continuation 4-space indent triggers Q-2-35; structurally analogous to q2#196 but for footnotes)",
    "docs/authoring/cross-references.qmd"                          = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/authoring/markdown-basics.qmd"                           = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/authoring/tables.qmd"                                    = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/blog/posts/2023-12-07-quarto-dashboards-demo/index.qmd"  = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/blog/posts/2024-01-24-1.4-release/index.qmd"             = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/blog/posts/2024-12-04-websites-workshop/index.qmd"       = "q2#TBD-underscore-prefix-emphasis (Q-2-5 on _filename.ext identifiers)",
    "docs/blog/posts/2025-10-20-quarto-wizard-1-0-0/index.qmd"     = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/blog/posts/2025-11-24-conf-talk-videos/index.qmd"        = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/computations/caching.qmd"                                = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/computations/julia.qmd"                                  = "q2#TBD-apostrophe-quote-close (Q-2-9/Q-2-10 on possessive apostrophes)",
    "docs/computations/r.qmd"                                      = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/dashboards/_examples/penguins-obervable.qmd"             = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/extensions/filters.qmd"                                  = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/extensions/lua.qmd"                                      = "q2#TBD-attr-key-before-class (Q-2-3 fires on {key='v' .class} attribute ordering)",
    "docs/extensions/project-types.qmd"                            = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/get-started/authoring/jupyter.qmd"                       = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/authoring/rstudio.qmd"                       = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/computations/jupyter.qmd"                    = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/computations/positron.qmd"                   = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/computations/vscode.qmd"                     = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/hello/jupyter.qmd"                           = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/hello/neovim.qmd"                            = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/hello/text-editor.qmd"                       = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/hello/vscode.qmd"                            = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/interactive/layout.qmd"                                  = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/interactive/ojs/libraries.qmd"                           = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/interactive/ojs/ojs-cells.qmd"                           = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/interactive/ojs/shiny.qmd"                               = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/interactive/shiny/execution.qmd"                         = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/interactive/shiny/index.qmd"                             = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/manuscripts/authoring/_citations.qmd"                    = "q2#TBD-attr-key-before-class (Q-2-3 fires on {key='v' .class} attribute ordering)",
    "docs/manuscripts/authoring/_structure.qmd"                    = "q2#TBD-inline-span-triple-backtick (inline code span wrapping ` ```{lang} ` rejected)",
    "docs/manuscripts/authoring/_visual-editor.qmd"                = "q2#TBD-attr-key-before-class (Q-2-3 fires on {key='v' .class} attribute ordering)",
    "docs/manuscripts/components.qmd"                              = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/manuscripts/index.qmd"                                   = "q2#TBD-attr-key-before-class (Q-2-3 fires on {key='v' .class} attribute ordering)",
    "docs/output-formats/html-code.qmd"                            = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/output-formats/html-themes-more.qmd"                     = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/output-formats/hugo.qmd"                                 = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/output-formats/ms-word-templates.qmd"                    = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/output-formats/typst-custom.qmd"                         = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/presentations/revealjs/presenting.qmd"                   = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/projects/code-execution.qmd"                             = "q2#TBD-apostrophe-quote-close (Q-2-9/Q-2-10 on possessive apostrophes)",
    "docs/projects/quarto-projects.qmd"                            = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/projects/virtual-environments.qmd"                       = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/publishing/github-pages.qmd"                             = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/tools/_jupyter-lab-extension-install.qmd"                = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/tools/jupyter-lab-extension.qmd"                         = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/tools/jupyter-lab.qmd"                                   = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/visual-editor/options.qmd"                               = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/visual-editor/technical.qmd"                             = "q2#TBD-inline-span-triple-backtick (inline code span wrapping ` ```{lang} ` rejected)",
    "docs/websites/website-drafts.qmd"                             = "q2#TBD-apostrophe-quote-close (Q-2-9/Q-2-10 on possessive apostrophes)",
    "docs/websites/website-listings-custom.qmd"                    = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/websites/website-listings.qmd"                           = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/websites/website-navigation.qmd"                         = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/websites/website-tools.qmd"                              = "q2#TBD-apostrophe-quote-close (Q-2-9/Q-2-10 on possessive apostrophes)"
  ),
  pampa_pd_rt = list(
    "_tools/screenshots/examples/quarto-demo/crossref-jupyter.qmd" = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "bug-reports.qmd"                                              = "q2#TBD-inline-span-triple-backtick (inline code span wrapping ` ```{lang} ` rejected)",
    "docs/advanced/environment-vars.qmd"                           = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/authoring/create-citeable-articles.qmd"                  = "q2#TBD-footnote-indent-continuation (footnote-continuation 4-space indent triggers Q-2-35; structurally analogous to q2#196 but for footnotes)",
    "docs/authoring/cross-references.qmd"                          = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/authoring/markdown-basics.qmd"                           = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/authoring/tables.qmd"                                    = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/blog/posts/2023-12-07-quarto-dashboards-demo/index.qmd"  = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/blog/posts/2024-01-24-1.4-release/index.qmd"             = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/blog/posts/2024-04-01-manuscripts-rmedicine/index.qmd"   = "q2#174 (loose list tightened on round-trip)",
    "docs/blog/posts/2024-12-04-websites-workshop/index.qmd"       = "q2#TBD-underscore-prefix-emphasis (Q-2-5 on _filename.ext identifiers)",
    "docs/blog/posts/2025-10-20-quarto-wizard-1-0-0/index.qmd"     = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/blog/posts/2025-11-24-conf-talk-videos/index.qmd"        = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/computations/caching.qmd"                                = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/computations/julia.qmd"                                  = "q2#TBD-apostrophe-quote-close (Q-2-9/Q-2-10 on possessive apostrophes)",
    "docs/computations/r.qmd"                                      = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/dashboards/_examples/penguins-obervable.qmd"             = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/extensions/_shortcode-escaping.qmd"                      = "q2#174 (loose list tightened on round-trip)",
    "docs/extensions/filters.qmd"                                  = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/extensions/lua.qmd"                                      = "q2#TBD-attr-key-before-class (Q-2-3 fires on {key='v' .class} attribute ordering)",
    "docs/extensions/project-types.qmd"                            = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/get-started/authoring/jupyter.qmd"                       = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/authoring/rstudio.qmd"                       = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/computations/jupyter.qmd"                    = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/computations/positron.qmd"                   = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/computations/vscode.qmd"                     = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/hello/jupyter.qmd"                           = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/hello/neovim.qmd"                            = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/hello/rstudio.qmd"                           = "q2#174 (loose list tightened on round-trip)",
    "docs/get-started/hello/text-editor.qmd"                       = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/get-started/hello/vscode.qmd"                            = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/interactive/layout.qmd"                                  = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/interactive/ojs/libraries.qmd"                           = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/interactive/ojs/ojs-cells.qmd"                           = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/interactive/ojs/shiny.qmd"                               = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/interactive/shiny/execution.qmd"                         = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/interactive/shiny/index.qmd"                             = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/journals/authors.qmd"                                    = "q2#174 (loose list tightened on round-trip)",
    "docs/journals/formats.qmd"                                    = "q2#174 (loose list tightened on round-trip)",
    "docs/manuscripts/authoring/_citations.qmd"                    = "q2#TBD-attr-key-before-class (Q-2-3 fires on {key='v' .class} attribute ordering)",
    "docs/manuscripts/authoring/_setup.qmd"                        = "q2#174 (loose list tightened on round-trip)",
    "docs/manuscripts/authoring/_structure.qmd"                    = "q2#TBD-inline-span-triple-backtick (inline code span wrapping ` ```{lang} ` rejected)",
    "docs/manuscripts/authoring/_visual-editor.qmd"                = "q2#TBD-attr-key-before-class (Q-2-3 fires on {key='v' .class} attribute ordering)",
    "docs/manuscripts/components.qmd"                              = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/manuscripts/index.qmd"                                   = "q2#TBD-attr-key-before-class (Q-2-3 fires on {key='v' .class} attribute ordering)",
    "docs/output-formats/html-code.qmd"                            = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/output-formats/html-themes-more.qmd"                     = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/output-formats/hugo.qmd"                                 = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/output-formats/ms-word-templates.qmd"                    = "q2-design-indented-blocks (quarto-web doc uses 4-space-indented examples that Quarto Markdown rejects; not a q2 bug)",
    "docs/output-formats/typst-custom.qmd"                         = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/presentations/revealjs/index.qmd"                        = "q2#174 (loose list tightened on round-trip)",
    "docs/presentations/revealjs/presenting.qmd"                   = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/projects/code-execution.qmd"                             = "q2#TBD-apostrophe-quote-close (Q-2-9/Q-2-10 on possessive apostrophes)",
    "docs/projects/quarto-projects.qmd"                            = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/projects/virtual-environments.qmd"                       = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/publishing/github-pages.qmd"                             = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/tools/_jupyter-lab-extension-install.qmd"                = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/tools/jupyter-lab-extension.qmd"                         = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/tools/jupyter-lab.qmd"                                   = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/visual-editor/options.qmd"                               = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/visual-editor/technical.qmd"                             = "q2#TBD-inline-span-triple-backtick (inline code span wrapping ` ```{lang} ` rejected)",
    "docs/websites/website-blog.qmd"                               = "q2#174 (loose list tightened on round-trip)",
    "docs/websites/website-drafts.qmd"                             = "q2#TBD-apostrophe-quote-close (Q-2-9/Q-2-10 on possessive apostrophes)",
    "docs/websites/website-listings-custom.qmd"                    = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/websites/website-listings.qmd"                           = "q2#TBD-table-cell-grid-backticks (grid-table cells with ``` code fence trigger parse error)",
    "docs/websites/website-navigation.qmd"                         = "q2#TBD-misc-parse (one-off parser edge cases; see notes/parser_misc_edge_cases_notes.md)",
    "docs/websites/website-tools.qmd"                              = "q2#TBD-apostrophe-quote-close (Q-2-9/Q-2-10 on possessive apostrophes)"
  )
)



gen_test_block = function(rel, skip_map, body_lines) {
  reason = skip_map[[rel]]
  quoted = deparse(rel, width.cutoff = 500L)

  if (!is.null(reason)) {
    return(c(
      paste0("test_that(", quoted, ", {"),
      paste0("  skip(", deparse(paste0("Known failure: ", reason), width.cutoff = 500L), ")"),
      "})"
    ))
  }

  c(
    paste0("test_that(", quoted, ", {"),
    body_lines,
    "})"
  )
}

gen_ts_rt_test = function(rel, skip_map = list()) {
  gen_test_block(rel, skip_map, c(
    "  skip_if_no_quarto_web()",
    paste0("  text = quarto_web_read(", deparse(rel, width.cutoff = 500L), ")"),
    "  ts = pampa_parse_ts(text, quiet = TRUE)",
    "  expect_no_error_diagnostics(ts)",
    "  if (has_error_diagnostics(ts)) return(invisible())",
    "  rendered = to_qmd(ts)",
    "  ts2 = pampa_parse_ts(rendered, quiet = TRUE)",
    "  expect_no_error_diagnostics(ts2)",
    "  expect_ts_ast_equal(ts2, ts)"
  ))
}

gen_pd_rt_test = function(rel, skip_map = list()) {
  gen_test_block(rel, skip_map, c(
    "  skip_if_no_quarto_web()",
    paste0("  text = quarto_web_read(", deparse(rel, width.cutoff = 500L), ")"),
    "  pd = pampa_parse_pd(text, quiet = TRUE)",
    "  expect_no_error_diagnostics(pd)",
    "  if (has_error_diagnostics(pd)) return(invisible())",
    "  rendered = to_qmd(pd)",
    "  pd2 = pampa_parse_pd(rendered, quiet = TRUE)",
    "  expect_no_error_diagnostics(pd2)",
    "  expect_pd_ast_equal(pd2, pd)"
  ))
}


gen_pampa_pd_rt_test = function(rel, skip_map = list()) {
  gen_test_block(rel, skip_map, c(
    "  skip_if_no_quarto_web()",
    paste0("  text = quarto_web_read(", deparse(rel, width.cutoff = 500L), ")"),
    "  pd = pampa_parse_pd(text, quiet = TRUE)",
    "  expect_no_error_diagnostics(pd)",
    "  if (has_error_diagnostics(pd)) return(invisible())",
    "  rendered = pampa_to_qmd(pd)",
    "  pd2 = pampa_parse_pd(rendered, quiet = TRUE)",
    "  expect_no_error_diagnostics(pd2)",
    "  expect_pd_ast_equal(pd2, pd)"
  ))
}
