# Round-trip failures attributable to pampa's QMD writer (q2-issues.md):
# - list-marker normalization (Issue 4): * forced for all bullets, indent collapsed
# - figure / div-figure shape changes (Issue 3)
# These tests are skipped until upstream pampa is fixed; re-enable by
# regenerating tests after q2 bumps that resolve those issues.
PAMPA_QMD_WRITER_TS_FAIL = c(
  "_tools/screenshots/examples/about-pages/about-broadside.qmd",
  "_tools/screenshots/examples/about-pages/about-jolla.qmd",
  "_tools/screenshots/examples/about-pages/about-marquee.qmd",
  "_tools/screenshots/examples/about-pages/about-solana.qmd",
  "_tools/screenshots/examples/about-pages/about-trestles.qmd",
  "_tools/screenshots/examples/breadcrumbs/index.qmd",
  "_tools/screenshots/examples/breadcrumbs/tutorials.qmd",
  "_tools/screenshots/examples/hybrid-nav/fundamentals.qmd",
  "_tools/screenshots/examples/hybrid-nav/howto.qmd",
  "_tools/screenshots/examples/hybrid-nav/index.qmd",
  "_tools/screenshots/examples/hybrid-nav/reference.qmd",
  "_tools/screenshots/examples/hybrid-nav/tutorial-1.qmd",
  "_tools/screenshots/examples/hybrid-nav/tutorial-2.qmd",
  "_tools/screenshots/examples/hybrid-nav/tutorials.qmd",
  "_tools/screenshots/examples/myblog/about.qmd",
  "_tools/screenshots/examples/myblog/index.qmd",
  "_tools/screenshots/examples/myblog/posts/first-post/index.qmd",
  "_tools/screenshots/examples/myblog/posts/welcome/index.qmd",
  "_tools/screenshots/examples/navbar-basic/about.qmd",
  "_tools/screenshots/examples/navbar-basic/index.qmd",
  "_tools/screenshots/examples/navbar-basic/talks.qmd",
  "_tools/screenshots/examples/navbar-tools/index.qmd",
  "_tools/screenshots/examples/quarto-demo/basics-jupyter.qmd",
  "_tools/screenshots/examples/quarto-demo/layout-jupyter.qmd",
  "about.qmd",
  "docs/advanced/html/external-sources.qmd",
  "docs/advanced/index.qmd",
  "docs/advanced/inspect/index.qmd",
  "docs/advanced/jupyter/kernel-execution.qmd",
  "docs/advanced/latex-raw.qmd",
  "docs/advanced/quarto-ast.qmd",
  "docs/advanced/quarto-execute-info.qmd",
  "docs/advanced/typst/brand-yaml.qmd",
  "docs/advanced/typst/typst-css.qmd",
  "docs/advanced/typst/typst-gather.qmd",
  "docs/authoring/_brand-example.qmd",
  "docs/authoring/_cross-reference-divs-diagram.qmd",
  "docs/authoring/_cross-reference-divs-figure.qmd",
  "docs/authoring/_cross-reference-divs-listing.qmd",
  "docs/authoring/_cross-reference-divs-table.qmd",
  "docs/authoring/_cross-reference-divs-video.qmd",
  "docs/authoring/_cross-references-callouts.qmd",
  "docs/authoring/_cross-references-listings.qmd",
  "docs/authoring/_embed-examples/sample-notebook-view.qmd",
  "docs/authoring/_embed-examples/sample.qmd",
  "docs/authoring/_embeds-ipynb.qmd",
  "docs/authoring/_figure-examples/_examples.qmd",
  "docs/authoring/_kbd.qmd",
  "docs/authoring/_mermaid-examples/darkly.qmd",
  "docs/authoring/_mermaid-examples/solar.qmd",
  "docs/authoring/_mermaid-examples/vapor.qmd",
  "docs/authoring/_mermaid-theming.qmd",
  "docs/authoring/_pagebreak.qmd",
  "docs/authoring/_shortcodes.qmd",
  "docs/authoring/appendices.qmd",
  "docs/authoring/article-layout.qmd",
  "docs/authoring/brand.qmd",
  "docs/authoring/callouts.qmd",
  "docs/authoring/citations.qmd",
  "docs/authoring/code-annotation-example/revealjs.qmd",
  "docs/authoring/code-annotation.qmd",
  "docs/authoring/conditional.qmd",
  "docs/authoring/contents.qmd",
  "docs/authoring/create-citeable-articles.qmd",
  "docs/authoring/cross-reference-options.qmd",
  "docs/authoring/cross-references-custom.qmd",
  "docs/authoring/cross-references-divs.qmd",
  "docs/authoring/cross-references.qmd",
  "docs/authoring/diagrams.qmd",
  "docs/authoring/figures.qmd",
  "docs/authoring/front-matter.qmd",
  "docs/authoring/includes.qmd",
  "docs/authoring/language.qmd",
  "docs/authoring/lipsum.qmd",
  "docs/authoring/notebook-embed.qmd",
  "docs/authoring/penguins-qmd.qmd",
  "docs/authoring/placeholder.qmd",
  "docs/authoring/title-blocks.qmd",
  "docs/authoring/variables.qmd",
  "docs/authoring/version.qmd",
  "docs/authoring/videos.qmd",
  "docs/blog/index.qmd",
  "docs/blog/posts/2022-02-13-feature-callouts/index.qmd",
  "docs/blog/posts/2022-02-15-feature-tables/index.qmd",
  "docs/blog/posts/2022-02-17-advanced-layout/index.qmd",
  "docs/blog/posts/2022-06-21-rstudio-conf-2022-quarto/index.qmd",
  "docs/blog/posts/2022-07-25-feature-extensions/index.qmd",
  "docs/blog/posts/2022-10-25-shinylive-extension/index.qmd",
  "docs/blog/posts/2023-03-13-code-annotation/index.qmd",
  "docs/blog/posts/2023-03-15-multi-format/index.qmd",
  "docs/blog/posts/2023-03-17-jupyter-cell-embedding/index.qmd",
  "docs/blog/posts/2023-03-20-confluence/index.qmd",
  "docs/blog/posts/2023-04-26-1.3-release/index.qmd",
  "docs/blog/posts/2023-05-15-get-started/index.qmd",
  "docs/blog/posts/2023-05-22-quarto-for-academics/index.qmd",
  "docs/blog/posts/2023-12-05-asa-traveling-courses/index.qmd",
  "docs/blog/posts/2024-03-26-hugging-face/index.qmd",
  "docs/blog/posts/2024-04-01-manuscripts-rmedicine/index.qmd",
  "docs/blog/posts/2024-05-28-conf-workshops/index.qmd",
  "docs/blog/posts/2024-07-02-beautiful-tables-in-typst/examples/great-tables-oceania.qmd",
  "docs/blog/posts/2024-07-02-beautiful-tables-in-typst/examples/great-tables-solar-zenith.qmd",
  "docs/blog/posts/2024-07-02-beautiful-tables-in-typst/examples/gt-cars.qmd",
  "docs/blog/posts/2024-07-02-beautiful-tables-in-typst/examples/gt-islands.qmd",
  "docs/blog/posts/2024-07-02-beautiful-tables-in-typst/examples/pandas-acting-on-data.qmd",
  "docs/blog/posts/2024-07-02-beautiful-tables-in-typst/examples/pandas-confusion-matrix.qmd",
  "docs/blog/posts/2024-07-02-beautiful-tables-in-typst/index.qmd",
  "docs/blog/posts/2024-07-11-1.5-release/index.qmd",
  "docs/blog/posts/2024-10-15-conf-workshops-materials/index.qmd",
  "docs/blog/posts/2024-11-06-conf-talks/index.qmd",
  "docs/blog/posts/2024-11-22-dashboards-workshop/index.qmd",
  "docs/blog/posts/2024-11-25-1.6-release/index.qmd",
  "docs/blog/posts/2024-12-12-includes-meta/index.qmd",
  "docs/blog/posts/2025-01-15-quarto-tip-brand-positron/index.qmd",
  "docs/blog/posts/2025-04-28-1.7-release/index.qmd",
  "docs/blog/posts/2025-05-19-quarto-codespaces/index.qmd",
  "docs/blog/posts/2025-07-24-parameterized-reports-python/index.qmd",
  "docs/blog/posts/2025-07-28-R-package-release-1.5/index.qmd",
  "docs/blog/posts/2025-10-13-1.8-release/index.qmd",
  "docs/blog/posts/2025-10-27-conf-workshops-materials/index.qmd",
  "docs/blog/posts/2026-03-05-pdf-accessibility-and-standards/index.qmd",
  "docs/blog/posts/2026-03-24-1.9-release/index.qmd",
  "docs/blog/posts/2026-03-31-typst-books-and-more/index.qmd",
  "docs/blog/posts/2026-04-06-whats-next-quarto-2/index.qmd",
  "docs/blog/posts/2026-04-14-chrome-headless-shell/index.qmd",
  "docs/books/book-basics.qmd",
  "docs/books/book-crossrefs.qmd",
  "docs/books/book-output.qmd",
  "docs/books/book-structure.qmd",
  "docs/cli/add.qmd",
  "docs/cli/call.qmd",
  "docs/cli/capabilities.qmd",
  "docs/cli/check.qmd",
  "docs/cli/convert.qmd",
  "docs/cli/create.qmd",
  "docs/cli/index.qmd",
  "docs/cli/inspect.qmd",
  "docs/cli/install.qmd",
  "docs/cli/list.qmd",
  "docs/cli/pandoc.qmd",
  "docs/cli/preview.qmd",
  "docs/cli/publish.qmd",
  "docs/cli/remove.qmd",
  "docs/cli/render.qmd",
  "docs/cli/run.qmd",
  "docs/cli/serve.qmd",
  "docs/cli/tools.qmd",
  "docs/cli/typst.qmd",
  "docs/cli/uninstall.qmd",
  "docs/cli/update.qmd",
  "docs/cli/use.qmd",
  "docs/computations/execution-options.qmd",
  "docs/computations/inline-code.qmd",
  "docs/computations/ojs.qmd",
  "docs/computations/parameters.qmd",
  "docs/computations/python.qmd",
  "docs/computations/r.qmd",
  "docs/computations/render-scripts.qmd",
  "docs/dashboards/_examples/_TODO.qmd",
  "docs/dashboards/_examples/altair.qmd",
  "docs/dashboards/_examples/cell-layout.qmd",
  "docs/dashboards/_examples/flow.qmd",
  "docs/dashboards/_examples/gapminder-content.qmd",
  "docs/dashboards/_examples/gapminder.qmd",
  "docs/dashboards/_examples/inputs/card-toolbar.qmd",
  "docs/dashboards/_examples/inputs/column-layout.qmd",
  "docs/dashboards/_examples/inputs/inline-sidebar.qmd",
  "docs/dashboards/_examples/inputs/inline-toolbar.qmd",
  "docs/dashboards/_examples/inputs/input-panel.qmd",
  "docs/dashboards/_examples/inputs/page-sidebar.qmd",
  "docs/dashboards/_examples/inputs/right-sidebar.qmd",
  "docs/dashboards/_examples/inputs/toolbar.qmd",
  "docs/dashboards/_examples/julia/julia-plotly.qmd",
  "docs/dashboards/_examples/leaflet.qmd",
  "docs/dashboards/_examples/markdown.qmd",
  "docs/dashboards/_examples/navigation.qmd",
  "docs/dashboards/_examples/python-wide.qmd",
  "docs/dashboards/_examples/python/python-itables.qmd",
  "docs/dashboards/_examples/python/python-tabulate.qmd",
  "docs/dashboards/_examples/r/dt.qmd",
  "docs/dashboards/_examples/shiny-diamonds.qmd",
  "docs/dashboards/_examples/shiny-global-sidebar.qmd",
  "docs/dashboards/_examples/shiny-python-simple.qmd",
  "docs/dashboards/_examples/shiny-sidebar.qmd",
  "docs/dashboards/_examples/valuebox.qmd",
  "docs/dashboards/_inputs.qmd",
  "docs/dashboards/_layouts-old.qmd",
  "docs/dashboards/data-display.qmd",
  "docs/dashboards/deployment.qmd",
  "docs/dashboards/index.qmd",
  "docs/dashboards/inputs.qmd",
  "docs/dashboards/interactivity/index.qmd",
  "docs/dashboards/interactivity/observable.qmd",
  "docs/dashboards/interactivity/shiny-python/_shiny-requirements.qmd",
  "docs/dashboards/interactivity/shiny-python/execution.qmd",
  "docs/dashboards/interactivity/shiny-python/index.qmd",
  "docs/dashboards/interactivity/shiny-python/running.qmd",
  "docs/dashboards/interactivity/shiny-r.qmd",
  "docs/dashboards/layout.qmd",
  "docs/dashboards/parameters.qmd",
  "docs/dashboards/theming.qmd",
  "docs/download/changelog/1.1/index.qmd",
  "docs/download/changelog/1.2/index.qmd",
  "docs/download/changelog/1.3/index.qmd",
  "docs/download/changelog/1.4/index.qmd",
  "docs/download/index.qmd",
  "docs/download/prerelease.qmd",
  "docs/download/release.qmd",
  "docs/download/tarball.qmd",
  "docs/extensions/_extension-trust.qmd",
  "docs/extensions/_formats-common.qmd",
  "docs/extensions/_listing-chooser.qmd",
  "docs/extensions/_listing-footer.qmd",
  "docs/extensions/_listing-preamble.qmd",
  "docs/extensions/_shortcode-escaping.qmd",
  "docs/extensions/brand.qmd",
  "docs/extensions/creating.qmd",
  "docs/extensions/distributing.qmd",
  "docs/extensions/engine.qmd",
  "docs/extensions/filters.qmd",
  "docs/extensions/formats.qmd",
  "docs/extensions/index.qmd",
  "docs/extensions/listing-filters.qmd",
  "docs/extensions/listing-formats.qmd",
  "docs/extensions/listing-journals.qmd",
  "docs/extensions/listing-revealjs.qmd",
  "docs/extensions/lua-api.qmd",
  "docs/extensions/managing.qmd",
  "docs/extensions/metadata.qmd",
  "docs/extensions/nbfilter.qmd",
  "docs/extensions/revealjs.qmd",
  "docs/extensions/shortcodes.qmd",
  "docs/extensions/starter-templates.qmd",
  "docs/faq/index.qmd",
  "docs/faq/rmarkdown.qmd",
  "docs/gallery/index.qmd",
  "docs/get-started/authoring/_authoring-complete.qmd",
  "docs/get-started/authoring/_authoring.qmd",
  "docs/get-started/authoring/index.qmd",
  "docs/get-started/authoring/neovim.qmd",
  "docs/get-started/authoring/positron.qmd",
  "docs/get-started/authoring/text-editor.qmd",
  "docs/get-started/authoring/vscode.qmd",
  "docs/get-started/computations/_computations-complete.qmd",
  "docs/get-started/computations/_computations.qmd",
  "docs/get-started/computations/_positron/r/computations-complete.qmd",
  "docs/get-started/computations/rstudio.qmd",
  "docs/get-started/hello/_hello.qmd",
  "docs/get-started/hello/_positron/python/hello.qmd",
  "docs/get-started/hello/_positron/r/hello.qmd",
  "docs/get-started/hello/index.qmd",
  "docs/get-started/hello/positron.qmd",
  "docs/get-started/hello/rstudio.qmd",
  "docs/get-started/hello/rstudio/_hello.qmd",
  "docs/get-started/index.qmd",
  "docs/guide/index.qmd",
  "docs/interactive/index.qmd",
  "docs/interactive/layout.qmd",
  "docs/interactive/ojs/_reactivity.qmd",
  "docs/interactive/ojs/code-reuse.qmd",
  "docs/interactive/ojs/data-sources.qmd",
  "docs/interactive/ojs/examples/_shiny/binning/binning-shiny-ojs.qmd",
  "docs/interactive/ojs/examples/_shiny/data/data-shiny-ojs.qmd",
  "docs/interactive/ojs/examples/_shiny/kmeans/kmeans-shiny-ojs.qmd",
  "docs/interactive/ojs/examples/arquero.qmd",
  "docs/interactive/ojs/examples/github.qmd",
  "docs/interactive/ojs/examples/layout.qmd",
  "docs/interactive/ojs/examples/noaa-co2.qmd",
  "docs/interactive/ojs/examples/penguins.qmd",
  "docs/interactive/ojs/examples/population.qmd",
  "docs/interactive/ojs/examples/sunburst.qmd",
  "docs/interactive/ojs/index.qmd",
  "docs/interactive/ojs/libraries.qmd",
  "docs/interactive/ojs/ojs-cells.qmd",
  "docs/interactive/ojs/shiny.qmd",
  "docs/interactive/shiny/_examples/covid19-bicartogram/covid19-bicartogram.qmd",
  "docs/interactive/shiny/_examples/diamonds/shiny-diamonds.qmd",
  "docs/interactive/shiny/_examples/k-means/shiny-k-means.qmd",
  "docs/interactive/shiny/_examples/old-faithful/shiny-old-faithful.qmd",
  "docs/interactive/shiny/execution.qmd",
  "docs/interactive/shiny/index.qmd",
  "docs/interactive/shiny/resources.qmd",
  "docs/interactive/shiny/running.qmd",
  "docs/interactive/widgets/htmlwidgets.qmd",
  "docs/interactive/widgets/jupyter.qmd",
  "docs/journals/_draft/create-extensions.qmd",
  "docs/journals/_draft/extension-templates.qmd",
  "docs/journals/authors.qmd",
  "docs/journals/formats.qmd",
  "docs/journals/index.qmd",
  "docs/journals/templates.qmd",
  "docs/manuscripts/authoring/_authoring-content.qmd",
  "docs/manuscripts/authoring/_cross-refs.qmd",
  "docs/manuscripts/authoring/_embeds-ipynb.qmd",
  "docs/manuscripts/authoring/_embeds-qmd.qmd",
  "docs/manuscripts/authoring/_equations.qmd",
  "docs/manuscripts/authoring/_figures.qmd",
  "docs/manuscripts/authoring/_files.qmd",
  "docs/manuscripts/authoring/_front-matter.qmd",
  "docs/manuscripts/authoring/_inline-computations.qmd",
  "docs/manuscripts/authoring/_markdown.qmd",
  "docs/manuscripts/authoring/_overview.qmd",
  "docs/manuscripts/authoring/_setup.qmd",
  "docs/manuscripts/authoring/_tables.qmd",
  "docs/manuscripts/authoring/_workflow-ipynb.qmd",
  "docs/manuscripts/authoring/_workflow-qmd.qmd",
  "docs/manuscripts/authoring/_workflow.qmd",
  "docs/manuscripts/authoring/index.qmd",
  "docs/manuscripts/authoring/jupyterlab.qmd",
  "docs/manuscripts/authoring/rstudio.qmd",
  "docs/manuscripts/authoring/vscode.qmd",
  "docs/manuscripts/components.qmd",
  "docs/manuscripts/next-steps.qmd",
  "docs/manuscripts/publishing.qmd",
  "docs/output-formats/_ssg-intro.qmd",
  "docs/output-formats/_ssg-workflow.qmd",
  "docs/output-formats/all-formats.qmd",
  "docs/output-formats/docusaurus.qmd",
  "docs/output-formats/examples/gt-temps.qmd",
  "docs/output-formats/examples/pandas-temps.qmd",
  "docs/output-formats/gfm.qmd",
  "docs/output-formats/html-accessibility.qmd",
  "docs/output-formats/html-basics.qmd",
  "docs/output-formats/html-code.qmd",
  "docs/output-formats/html-lightbox-figures.qmd",
  "docs/output-formats/html-multi-format.qmd",
  "docs/output-formats/html-publishing.qmd",
  "docs/output-formats/html-themes-more.qmd",
  "docs/output-formats/html-themes.qmd",
  "docs/output-formats/hugo.qmd",
  "docs/output-formats/ms-word.qmd",
  "docs/output-formats/page-layout.qmd",
  "docs/output-formats/pdf-basics.qmd",
  "docs/output-formats/pdf-engine.qmd",
  "docs/output-formats/typst.qmd",
  "docs/prerelease/1.10/_highlights.qmd",
  "docs/prerelease/1.3/_highlights.qmd",
  "docs/prerelease/1.3/ast.qmd",
  "docs/prerelease/1.3/custom-ast-nodes/callout.qmd",
  "docs/prerelease/1.3/custom-ast-nodes/conditional-block.qmd",
  "docs/prerelease/1.3/custom-ast-nodes/tabset.qmd",
  "docs/prerelease/1.3/index.qmd",
  "docs/prerelease/1.3/pdf.qmd",
  "docs/prerelease/1.3/tables.qmd",
  "docs/prerelease/1.3/website-nav.qmd",
  "docs/prerelease/1.4/_highlights.qmd",
  "docs/prerelease/1.4/ast.qmd",
  "docs/prerelease/1.4/crossref.qmd",
  "docs/prerelease/1.4/email.qmd",
  "docs/prerelease/1.4/index.qmd",
  "docs/prerelease/1.4/lua_changes.qmd",
  "docs/prerelease/1.5/_highlights.qmd",
  "docs/prerelease/1.6/_highlights.qmd",
  "docs/prerelease/1.7/_highlights.qmd",
  "docs/prerelease/1.8/_highlights.qmd",
  "docs/prerelease/1.9/_highlights.qmd",
  "docs/presentations/beamer.qmd",
  "docs/presentations/index.qmd",
  "docs/presentations/powerpoint.qmd",
  "docs/presentations/revealjs/_callout-auto-stretch-scrollable.qmd",
  "docs/presentations/revealjs/advanced.qmd",
  "docs/presentations/revealjs/demo/index.qmd",
  "docs/presentations/revealjs/demo/mini/auto-animate-code.qmd",
  "docs/presentations/revealjs/demo/mini/auto-animate-movement.qmd",
  "docs/presentations/revealjs/demo/mini/auto-animate-stack.qmd",
  "docs/presentations/revealjs/demo/mini/auto-animate.qmd",
  "docs/presentations/revealjs/demo/mini/fragments-custom.qmd",
  "docs/presentations/revealjs/demo/mini/fragments-nested.qmd",
  "docs/presentations/revealjs/demo/mini/fragments.qmd",
  "docs/presentations/revealjs/demo/mini/stack.qmd",
  "docs/presentations/revealjs/examples/_theme-dark.qmd",
  "docs/presentations/revealjs/examples/background-no-title.qmd",
  "docs/presentations/revealjs/examples/columns.qmd",
  "docs/presentations/revealjs/examples/creating-slides-1.qmd",
  "docs/presentations/revealjs/examples/creating-slides-2.qmd",
  "docs/presentations/revealjs/examples/creating-slides-3.qmd",
  "docs/presentations/revealjs/examples/footer-and-logo.qmd",
  "docs/presentations/revealjs/examples/image-background.qmd",
  "docs/presentations/revealjs/examples/incremental-lists-1.qmd",
  "docs/presentations/revealjs/examples/incremental-lists-2.qmd",
  "docs/presentations/revealjs/examples/incremental-lists-3.qmd",
  "docs/presentations/revealjs/examples/index.qmd",
  "docs/presentations/revealjs/examples/no-footer-on-a-slide.qmd",
  "docs/presentations/revealjs/examples/per-slide-footer.qmd",
  "docs/presentations/revealjs/examples/slide-with-speaker-notes.qmd",
  "docs/presentations/revealjs/index.qmd",
  "docs/presentations/revealjs/themes.qmd",
  "docs/projects/binder.qmd",
  "docs/projects/environment.qmd",
  "docs/projects/profiles.qmd",
  "docs/projects/scripts.qmd",
  "docs/publishing/ci.qmd",
  "docs/publishing/confluence.qmd",
  "docs/publishing/hugging-face.qmd",
  "docs/publishing/index.qmd",
  "docs/publishing/netlify.qmd",
  "docs/publishing/other.qmd",
  "docs/publishing/posit-cloud.qmd",
  "docs/publishing/posit-connect-cloud.qmd",
  "docs/publishing/quarto-pub.qmd",
  "docs/publishing/rstudio-connect.qmd",
  "docs/reference/cells/cells-knitr.qmd",
  "docs/reference/cells/index.qmd",
  "docs/reference/dates.qmd",
  "docs/reference/formats/asciidoc.qmd",
  "docs/reference/formats/context.qmd",
  "docs/reference/formats/dashboard.qmd",
  "docs/reference/formats/docbook.qmd",
  "docs/reference/formats/docx.qmd",
  "docs/reference/formats/epub.qmd",
  "docs/reference/formats/fb2.qmd",
  "docs/reference/formats/haddock.qmd",
  "docs/reference/formats/html.qmd",
  "docs/reference/formats/icml.qmd",
  "docs/reference/formats/ipynb.qmd",
  "docs/reference/formats/jats.qmd",
  "docs/reference/formats/man.qmd",
  "docs/reference/formats/markdown/commonmark.qmd",
  "docs/reference/formats/markdown/gfm.qmd",
  "docs/reference/formats/markdown/hugo.qmd",
  "docs/reference/formats/markdown/markua.qmd",
  "docs/reference/formats/ms.qmd",
  "docs/reference/formats/muse.qmd",
  "docs/reference/formats/odt.qmd",
  "docs/reference/formats/opml.qmd",
  "docs/reference/formats/org.qmd",
  "docs/reference/formats/pdf.qmd",
  "docs/reference/formats/presentations/beamer.qmd",
  "docs/reference/formats/presentations/pptx.qmd",
  "docs/reference/formats/presentations/revealjs.qmd",
  "docs/reference/formats/rst.qmd",
  "docs/reference/formats/rtf.qmd",
  "docs/reference/formats/tei.qmd",
  "docs/reference/formats/texinfo.qmd",
  "docs/reference/formats/textile.qmd",
  "docs/reference/formats/typst.qmd",
  "docs/reference/formats/wiki/dokuwiki.qmd",
  "docs/reference/formats/wiki/jira.qmd",
  "docs/reference/formats/wiki/mediawiki.qmd",
  "docs/reference/formats/wiki/xwiki.qmd",
  "docs/reference/formats/wiki/zimwiki.qmd",
  "docs/reference/globs.qmd",
  "docs/reference/index.qmd",
  "docs/reference/metadata/brand.qmd",
  "docs/reference/metadata/citation.qmd",
  "docs/reference/projects/books.qmd",
  "docs/reference/projects/manuscripts.qmd",
  "docs/reference/projects/options.qmd",
  "docs/reference/projects/websites.qmd",
  "docs/tools/_examples/diagrams.qmd",
  "docs/tools/_examples/python.qmd",
  "docs/tools/neovim.qmd",
  "docs/tools/positron/index.qmd",
  "docs/tools/positron/visual-editor.qmd",
  "docs/tools/rstudio.qmd",
  "docs/tools/text-editors.qmd",
  "docs/tools/vscode/index.qmd",
  "docs/tools/vscode/notebook.qmd",
  "docs/tools/vscode/visual-editor.qmd",
  "docs/triaging/index.qmd",
  "docs/troubleshooting/index.qmd",
  "docs/visual-editor/content.qmd",
  "docs/visual-editor/index.qmd",
  "docs/visual-editor/markdown.qmd",
  "docs/websites/website-about.qmd",
  "docs/websites/website-basics.qmd",
  "docs/websites/website-blog.qmd",
  "docs/websites/website-llms.qmd",
  "docs/websites/website-search.qmd",
  "index.qmd",
  "license.qmd",
  "trademark.qmd"
)

PAMPA_QMD_WRITER_PD_FAIL = c(
  "docs/authoring/_cross-references-callouts.qmd",
  "docs/authoring/_figure-examples/_examples.qmd",
  "docs/authoring/_mermaid-theming.qmd",
  "docs/authoring/article-layout.qmd",
  "docs/authoring/brand.qmd",
  "docs/authoring/callouts.qmd",
  "docs/authoring/create-citeable-articles.qmd",
  "docs/authoring/cross-references-custom.qmd",
  "docs/authoring/cross-references-divs.qmd",
  "docs/authoring/figures.qmd",
  "docs/authoring/front-matter.qmd",
  "docs/authoring/includes.qmd",
  "docs/blog/posts/2022-07-25-feature-extensions/index.qmd",
  "docs/blog/posts/2023-03-20-confluence/index.qmd",
  "docs/blog/posts/2023-04-26-1.3-release/index.qmd",
  "docs/blog/posts/2023-12-05-asa-traveling-courses/index.qmd",
  "docs/blog/posts/2024-04-01-manuscripts-rmedicine/index.qmd",
  "docs/blog/posts/2024-07-02-beautiful-tables-in-typst/examples/great-tables-oceania.qmd",
  "docs/blog/posts/2024-07-02-beautiful-tables-in-typst/examples/great-tables-solar-zenith.qmd",
  "docs/blog/posts/2024-07-02-beautiful-tables-in-typst/examples/gt-cars.qmd",
  "docs/blog/posts/2024-07-02-beautiful-tables-in-typst/examples/gt-islands.qmd",
  "docs/blog/posts/2024-07-02-beautiful-tables-in-typst/examples/pandas-acting-on-data.qmd",
  "docs/blog/posts/2024-07-02-beautiful-tables-in-typst/examples/pandas-confusion-matrix.qmd",
  "docs/blog/posts/2024-07-02-beautiful-tables-in-typst/index.qmd",
  "docs/blog/posts/2024-07-11-1.5-release/index.qmd",
  "docs/blog/posts/2025-04-28-1.7-release/index.qmd",
  "docs/blog/posts/2025-07-24-parameterized-reports-python/index.qmd",
  "docs/blog/posts/2025-07-28-R-package-release-1.5/index.qmd",
  "docs/blog/posts/2026-03-24-1.9-release/index.qmd",
  "docs/blog/posts/2026-03-31-typst-books-and-more/index.qmd",
  "docs/computations/execution-options.qmd",
  "docs/dashboards/_examples/python/python-itables.qmd",
  "docs/dashboards/_layouts-old.qmd",
  "docs/dashboards/deployment.qmd",
  "docs/dashboards/index.qmd",
  "docs/extensions/_listing-chooser.qmd",
  "docs/extensions/_shortcode-escaping.qmd",
  "docs/extensions/creating.qmd",
  "docs/extensions/filters.qmd",
  "docs/extensions/lua-api.qmd",
  "docs/extensions/revealjs.qmd",
  "docs/extensions/shortcodes.qmd",
  "docs/gallery/index.qmd",
  "docs/get-started/hello/rstudio.qmd",
  "docs/interactive/index.qmd",
  "docs/journals/authors.qmd",
  "docs/journals/formats.qmd",
  "docs/manuscripts/authoring/_equations.qmd",
  "docs/manuscripts/authoring/_inline-computations.qmd",
  "docs/manuscripts/authoring/_setup.qmd",
  "docs/output-formats/all-formats.qmd",
  "docs/output-formats/examples/gt-temps.qmd",
  "docs/output-formats/examples/pandas-temps.qmd",
  "docs/output-formats/html-code.qmd",
  "docs/output-formats/html-lightbox-figures.qmd",
  "docs/output-formats/html-publishing.qmd",
  "docs/output-formats/hugo.qmd",
  "docs/output-formats/page-layout.qmd",
  "docs/output-formats/typst.qmd",
  "docs/prerelease/1.4/ast.qmd",
  "docs/presentations/revealjs/demo/index.qmd",
  "docs/presentations/revealjs/examples/index.qmd",
  "docs/presentations/revealjs/index.qmd",
  "docs/publishing/confluence.qmd",
  "docs/publishing/hugging-face.qmd",
  "docs/websites/website-blog.qmd",
  "index.qmd"
)

pampa_writer_skip = function(files) {
  reason = "pampa qmd writer round-trip (see q2-issues.md)"
  setNames(as.list(rep(reason, length(files))), files)
}

QUARTO_WEB_SKIP = list(
  ts_rt        = list(),
  pd_rt        = list(),
  pampa_ts_rt  = pampa_writer_skip(PAMPA_QMD_WRITER_TS_FAIL),
  pampa_pd_rt  = pampa_writer_skip(PAMPA_QMD_WRITER_PD_FAIL)
)


gen_test_block = function(rel, skip_map, body_lines) {
  reason = skip_map[[rel]]
  quoted = deparse(rel, width.cutoff = 500L)

  if (!is.null(reason)) {
    return(c(
      paste0("test_that(", quoted, ", {"),
      paste0("  skip(", deparse(paste0("Known failure: ", reason), width.cutoff = 500L), ")"),
      "})"
    ))
  }

  c(
    paste0("test_that(", quoted, ", {"),
    body_lines,
    "})"
  )
}

gen_ts_rt_test = function(rel, skip_map = list()) {
  gen_test_block(rel, skip_map, c(
    "  skip_if_no_quarto_web()",
    paste0("  text = quarto_web_read(", deparse(rel, width.cutoff = 500L), ")"),
    "  ts = pampa_parse_ts(text, quiet = TRUE)",
    "  if (has_error_diagnostics(ts)) skip(\"initial parse produced error diagnostics\")",
    "  rendered = to_qmd(ts)",
    "  ts2 = pampa_parse_ts(rendered, quiet = TRUE)",
    "  expect_no_error_diagnostics(ts2)",
    "  expect_ts_ast_equal(ts2, ts)"
  ))
}

gen_pd_rt_test = function(rel, skip_map = list()) {
  gen_test_block(rel, skip_map, c(
    "  skip_if_no_quarto_web()",
    paste0("  text = quarto_web_read(", deparse(rel, width.cutoff = 500L), ")"),
    "  pd = pampa_parse_pd(text, quiet = TRUE)",
    "  if (has_error_diagnostics(pd)) skip(\"initial parse produced error diagnostics\")",
    "  rendered = to_qmd(pd)",
    "  pd2 = pampa_parse_pd(rendered, quiet = TRUE)",
    "  expect_no_error_diagnostics(pd2)",
    "  expect_pd_ast_equal(pd2, pd)"
  ))
}

gen_pampa_ts_rt_test = function(rel, skip_map = list()) {
  gen_test_block(rel, skip_map, c(
    "  skip_if_no_quarto_web()",
    paste0("  text = quarto_web_read(", deparse(rel, width.cutoff = 500L), ")"),
    "  ts = pampa_parse_ts(text, quiet = TRUE)",
    "  if (has_error_diagnostics(ts)) skip(\"initial parse produced error diagnostics\")",
    "  rendered = pampa_to_qmd(ts)",
    "  ts2 = pampa_parse_ts(rendered, quiet = TRUE)",
    "  expect_no_error_diagnostics(ts2)",
    "  expect_ts_ast_equal(ts2, ts)"
  ))
}

gen_pampa_pd_rt_test = function(rel, skip_map = list()) {
  gen_test_block(rel, skip_map, c(
    "  skip_if_no_quarto_web()",
    paste0("  text = quarto_web_read(", deparse(rel, width.cutoff = 500L), ")"),
    "  pd = pampa_parse_pd(text, quiet = TRUE)",
    "  if (has_error_diagnostics(pd)) skip(\"initial parse produced error diagnostics\")",
    "  rendered = pampa_to_qmd(pd)",
    "  pd2 = pampa_parse_pd(rendered, quiet = TRUE)",
    "  expect_no_error_diagnostics(pd2)",
    "  expect_pd_ast_equal(pd2, pd)"
  ))
}
